apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  type: ClusterIP
  selector:
    app: application
  ports:
    - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-service
spec:
  type: ClusterIP
  selector:
    app: shadow
  ports:
    - port: 8080