apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: bitxon/app
      docker:
        dockerfile: Dockerfile.js
manifests:
  rawYaml:
    - k8s/auth-secret.yaml
    - k8s/app-service.yaml
    - k8s/app-deployment.yaml
    - k8s/app-ingress.yaml
